import { Poppins } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./css/globals.css";
import "./css/typography.css";
import "./css/colors.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Paw Privileges",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable}`}>{children}</body>
    </html>
  );
}
