export const SponsorTableData = [
  {
    name: "Jenny Wilson",
    email: "alma.lawson@example.com",
    createdAt: "2025-02-28T12:00:00.000Z",
    location: "Poland",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "Michael Brown",
    email: "michael.brown@example.com",
    createdAt: "2025-02-27T15:30:00.000Z",
    location: "United States",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "Sofia Martinez",
    email: "sofia.martinez@example.com",
    createdAt: "2025-02-26T09:45:00.000Z",
    location: "Spain",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "Liam Anderson",
    email: "liam.anderson@example.com",
    createdAt: "2025-02-25T18:10:00.000Z",
    location: "Canada",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "Emma Taylor",
    email: "emma.taylor@example.com",
    createdAt: "2025-02-24T22:20:00.000Z",
    location: "United Kingdom",
    image: "/images/svgs/profile.svg",
  },
];

export const UerBreederBody = [
  {
    name: "John Doe",
    email: "john.doe@example.com",
    type: "Labrador Breeder",
    dog: "Labrador Retriever",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "Jane Smith",
    email: "jane.smith@example.com",
    type: "German Shepherd Breeder",
    dog: "German Shepherd",
    date: "2025-02-24T22:20:00.000Z",
    location: "Los Angeles, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "Michael Brown",
    email: "michael.brown@example.com",
    type: "Golden Retriever Breeder",
    dog: "Golden Retriever",
    date: "2025-02-24T22:20:00.000Z",
    location: "Chicago, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "Emily Johnson",
    email: "emily.johnson@example.com",
    type: "Poodle Breeder",
    dog: "Poodle",
    date: "2025-02-24T22:20:00.000Z",
    location: "Miami, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "Robert Wilson",
    email: "robert.wilson@example.com",
    type: "Bulldog Breeder",
    dog: "Bulldog",
    date: "2025-02-24T22:20:00.000Z",
    location: "Houston, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "Sophia Martinez",
    email: "sophia.martinez@example.com",
    type: "Beagle Breeder",
    dog: "Beagle",
    date: "2025-02-24T22:20:00.000Z",
    location: "San Francisco, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "Daniel Lee",
    email: "daniel.lee@example.com",
    type: "Rottweiler Breeder",
    dog: "Rottweiler",
    date: "2025-02-24T22:20:00.000Z",
    location: "Dallas, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "Olivia Anderson",
    email: "olivia.anderson@example.com",
    type: "Dachshund Breeder",
    dog: "Dachshund",
    date: "2025-02-24T22:20:00.000Z",
    location: "Seattle, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "William Thomas",
    email: "william.thomas@example.com",
    type: "Siberian Husky Breeder",
    dog: "Siberian Husky",
    date: "2025-02-24T22:20:00.000Z",
    location: "Denver, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "Ava White",
    email: "ava.white@example.com",
    type: "Shih Tzu Breeder",
    dog: "Shih Tzu",
    date: "2025-02-24T22:20:00.000Z",
    location: "Boston, USA",
    image: "/images/svgs/profile.svg",
  },
];

export const UerOwnerBody = [
  {
    name: "John Doe",
    email: "john.doe@example.com",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
];

export const UerSponsorBody = [
  {
    name: "John Doe",
    email: "john.doe@example.com",
    registrationType: "By Admin",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    registrationType: "By Admin",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    registrationType: "By Admin",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    registrationType: "By Admin",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    registrationType: "By Admin",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    registrationType: "By Admin",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    registrationType: "By Admin",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    registrationType: "By Admin",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    registrationType: "By Admin",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
  {
    name: "John Doe",
    email: "john.doe@example.com",
    registrationType: "By Admin",
    date: "2024-02-20",
    location: "New York, USA",
    image: "/images/svgs/profile.svg",
  },
];

export const directoryTableData = [
  {
    id: 1,
    name: "John Doe",
    location: "New York",
    addedDate: "2025-01-01",
    contact: "123-456-7890",
    image: "/images/svgs/profile.svg",
  },
  {
    id: 2,
    name: "Jane Smith",
    location: "Los Angeles",
    addedDate: "2025-01-02",
    contact: "987-654-3210",
    image: "/images/svgs/profile.svg",
  },
  {
    id: 3,
    name: "Alice Johnson",
    location: "Chicago",
    addedDate: "2025-01-03",
    contact: "456-789-0123",
    image: "/images/svgs/profile.svg",
  },
  {
    id: 4,
    name: "Bob Brown",
    location: "Houston",
    addedDate: "2025-01-04",
    contact: "654-321-0987",
    image: "/images/svgs/profile.svg",
  },
  {
    id: 5,
    name: "Charlie Davis",
    location: "Phoenix",
    addedDate: "2025-01-05",
    contact: "321-654-9870",
    image: "/images/svgs/profile.svg",
  },
  {
    id: 6,
    name: "Eve White",
    location: "Philadelphia",
    addedDate: "2025-01-06",
    contact: "654-987-3210",
    image: "/images/svgs/profile.svg",
  },
  {
    id: 7,
    name: "Frank Miller",
    location: "San Antonio",
    addedDate: "2025-01-07",
    contact: "789-012-3456",
    image: "/images/svgs/profile.svg",
  },
  {
    id: 8,
    name: "Grace Lee",
    location: "San Diego",
    addedDate: "2025-01-08",
    contact: "012-345-6789",
    image: "/images/svgs/profile.svg",
  },
  {
    id: 9,
    name: "Hank Wilson",
    location: "Dallas",
    addedDate: "2025-01-09",
    contact: "234-567-8901",
    image: "/images/svgs/profile.svg",
  },
  {
    id: 10,
    name: "Ivy Moore",
    location: "San Jose",
    addedDate: "2025-01-10",
    contact: "567-890-1234",
    image: "/images/svgs/profile.svg",
  },
  {
    id: 11,
    name: "Jack Taylor",
    location: "Austin",
    addedDate: "2025-01-11",
    contact: "890-123-4567",
    image: "/images/svgs/profile.svg",
  },
];

export const offerInPersonTableData = [
  {
    offerName: "Summer Discount",
    offerType: "In-Person",
    location: "New York",
    status: "approved",
    select: "",
  },
  {
    offerName: "Weekend Special",
    offerType: "In-Person",
    location: "Los Angeles",
    status: "rejected",
    select: "",
  },
  {
    offerName: "Flash Sale",
    offerType: "In-Person",
    location: "Chicago",
    status: "approved",
    select: "",
  },
  {
    offerName: "Holiday Bundle",
    offerType: "In-Person",
    location: "Houston",
    status: "approved",
    select: "",
  },
  {
    offerName: "VIP Exclusive",
    offerType: "In-Person",
    location: "Miami",
    status: "rejected",
    select: "",
  },
  {
    offerName: "Limited Time Deal",
    offerType: "In-Person",
    location: "San Francisco",
    status: "approved",
    select: "",
  },
  {
    offerName: "BOGO Offer",
    offerType: "In-Person",
    location: "Seattle",
    status: "pending",
    select: "",
  },
  {
    offerName: "Early Bird Special",
    offerType: "In-Person",
    location: "Boston",
    status: "rejected",
    select: "",
  },
  {
    offerName: "Loyalty Rewards",
    offerType: "In-Person",
    location: "Denver",
    status: "rejected",
    select: "",
  },
  {
    offerName: "Student Discount",
    offerType: "In-Person",
    location: "Dallas",
    status: "pending",
    select: "",
  },
];

export const offerOnlineTableData = [
  {
    offerName: "Summer Discount",
    offerType: "Online",
    location: "New York",
    status: "approved",
    select: "",
  },
  {
    offerName: "Weekend Special",
    offerType: "Online",
    location: "Los Angeles",
    status: "rejected",
    select: "",
  },
  {
    offerName: "Flash Sale",
    offerType: "Online",
    location: "Chicago",
    status: "rejected",
    select: "",
  },
  {
    offerName: "Holiday Bundle",
    offerType: "Online",
    location: "Houston",
    status: "pending",
    select: "",
  },
  {
    offerName: "VIP Exclusive",
    offerType: "Online",
    location: "Miami",
    status: "rejected",
    select: "",
  },
  {
    offerName: "Limited Time Deal",
    offerType: "Online",
    location: "San Francisco",
    status: "approved",
    select: "",
  },
  {
    offerName: "BOGO Offer",
    offerType: "Online",
    location: "Seattle",
    status: "approved",
    select: "",
  },
  {
    offerName: "Early Bird Special",
    offerType: "Online",
    location: "Boston",
    status: "rejected",
    select: "",
  },
  {
    offerName: "Loyalty Rewards",
    offerType: "Online",
    location: "Denver",
    status: "rejected",
    select: "",
  },
  {
    offerName: "Student Discount",
    offerType: "Online",
    location: "Dallas",
    status: "approved",
    select: "",
  },
];

export const billingDataRecords = [
  {
    name: "Alice Johnson",
    image: "/images/svgs/profile.svg",
    email: "alice@example.com",
    date: "2025-02-24T22:20:00.000Z",
    status: "paid",
    amount: "120.50",
    select: "",
  },
  {
    name: "Bob Smith",
    image: "/images/svgs/profile.svg",
    email: "bob@example.com",
    date: "2025-02-24T22:20:00.000Z",
    status: "pending",
    amount: "250.00",
    select: "",
  },
  {
    name: "Charlie Brown",
    image: "/images/svgs/profile.svg",
    email: "charlie@example.com",
    date: "2025-02-24T22:20:00.000Z",
    status: "paid",
    amount: "89.99",
    select: "",
  },
  {
    name: "David Lee",
    image: "/images/svgs/profile.svg",
    email: "david@example.com",
    date: "2025-02-24T22:20:00.000Z",
    status: "pending",
    amount: "300.75",
    select: "",
  },
  {
    name: "Emma Davis",
    image: "/images/svgs/profile.svg",
    email: "emma@example.com",
    date: "2025-02-24T22:20:00.000Z",
    status: "paid",
    amount: "150.30",
    select: "",
  },
  {
    name: "Frank Wilson",
    image: "/images/svgs/profile.svg",
    email: "frank@example.com",
    date: "2025-02-24T22:20:00.000Z",
    status: "pending",
    amount: "175.45",
    select: "",
  },
  {
    name: "Grace Hall",
    image: "/images/svgs/profile.svg",
    email: "grace@example.com",
    date: "2025-02-24T22:20:00.000Z",
    status: "paid",
    amount: "99.99",
    select: "",
  },
  {
    name: "Henry Adams",
    image: "/images/svgs/profile.svg",
    email: "henry@example.com",
    date: "2025-02-24T22:20:00.000Z",
    status: "pending",
    amount: "220.60",
    select: "",
  },
  {
    name: "Isabella White",
    image: "/images/svgs/profile.svg",
    email: "isabella@example.com",
    date: "2025-02-24T22:20:00.000Z",
    status: "paid",
    amount: "135.20",
    select: "",
  },
  {
    name: "Jack Miller",
    image: "/images/svgs/profile.svg",
    email: "jack@example.com",
    date: "2025-02-24T22:20:00.000Z",
    status: "pending",
    amount: "400.00",
    select: "",
  },
];
